import 'dotenv/config'
import { PrismaClient } from '../lib/generated/prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 시드 데이터 삽입 시작...')

  // 기존 데이터 삭제
  await prisma.review.deleteMany()
  await prisma.customerRequest.deleteMany()
  await prisma.contractor.deleteMany()

  // 설비 업체 대량 데이터 삽입 (25개 업체)
  const contractorData = [
    // 강남권 (5개)
    {
      name: '강남 누수119',
      phone: '02-538-1234',
      serviceArea: '강남구, 서초구',
      latitude: 37.4979,
      longitude: 127.0276,
      rating: 4.8,
      reviewCount: 127,
      completedJobs: 342,
      trustScore: 92.5,
      responseTime: 18,
      profileImage: '/contractors/plumber-1.png',
      description: '15년 경력의 누수 전문가입니다. 신속하고 정확한 진단으로 고객님의 불편을 해결해드립니다.',
      specialties: JSON.stringify(['누수탐지', '배관수리', '욕실리모델링']),
      verified: true,
      verifiedAt: new Date('2025-01-15'),
    },
    {
      name: '서초 배관마스터',
      phone: '02-587-5678',
      serviceArea: '서초구, 강남구, 송파구',
      latitude: 37.4837,
      longitude: 127.0324,
      rating: 4.9,
      reviewCount: 203,
      completedJobs: 567,
      trustScore: 95.8,
      responseTime: 15,
      profileImage: '/contractors/pipe-specialist-2.png',
      description: '서울대 건축학과 출신의 전문 배관기술자입니다. 정직한 시공, 합리적인 가격을 약속드립니다.',
      specialties: JSON.stringify(['배관공사', '하수구막힘', '수도배관교체']),
      verified: true,
      verifiedAt: new Date('2024-11-20'),
    },
    {
      name: '24시 압구정설비',
      phone: '1588-2222',
      serviceArea: '강남구 전역',
      latitude: 37.5274,
      longitude: 127.0286,
      rating: 4.7,
      reviewCount: 89,
      completedJobs: 234,
      trustScore: 88.3,
      responseTime: 25,
      profileImage: '/contractors/boiler-tech-3.png',
      description: '24시간 긴급출동 가능합니다. 보일러, 난방 전문.',
      specialties: JSON.stringify(['보일러수리', '난방공사', '긴급출동']),
      verified: true,
      verifiedAt: new Date('2025-02-01'),
    },
    {
      name: '삼성동 전기플러스',
      phone: '02-555-9090',
      serviceArea: '강남구, 서초구',
      latitude: 37.5146,
      longitude: 127.0632,
      rating: 4.6,
      reviewCount: 56,
      completedJobs: 178,
      trustScore: 85.1,
      responseTime: 32,
      profileImage: '/contractors/electrician-4.png',
      description: '전기기능사 자격증 보유. 안전한 전기공사를 약속드립니다.',
      specialties: JSON.stringify(['전기공사', '누전수리', '조명공사']),
      verified: true,
      verifiedAt: new Date('2025-01-10'),
    },
    {
      name: '역삼 싱크대클리닉',
      phone: '02-563-7777',
      serviceArea: '강남구',
      latitude: 37.5012,
      longitude: 127.0396,
      rating: 4.5,
      reviewCount: 42,
      completedJobs: 156,
      trustScore: 82.7,
      responseTime: 28,
      profileImage: '/contractors/sink-expert-5.png',
      description: '주방, 욕실 싱크대 전문 수리 업체입니다.',
      specialties: JSON.stringify(['싱크대수리', '배수구막힘', '수전교체']),
      verified: false,
    },

    // 서초권 (3개)
    {
      name: '서초 종합설비',
      phone: '02-521-3344',
      serviceArea: '서초구, 동작구',
      latitude: 37.4833,
      longitude: 127.0322,
      rating: 4.8,
      reviewCount: 134,
      completedJobs: 421,
      trustScore: 91.2,
      responseTime: 20,
      profileImage: '/contractors/plumber-1.png',
      description: '20년 전통의 설비 전문 업체입니다. 신뢰와 품질을 자랑합니다.',
      specialties: JSON.stringify(['종합설비', '배관', '보일러']),
      verified: true,
      verifiedAt: new Date('2024-12-05'),
    },
    {
      name: '반포 누수센터',
      phone: '02-532-8888',
      serviceArea: '서초구',
      latitude: 37.5030,
      longitude: 127.0015,
      rating: 4.9,
      reviewCount: 178,
      completedJobs: 489,
      trustScore: 94.3,
      responseTime: 12,
      profileImage: '/contractors/pipe-specialist-2.png',
      description: '반포 지역 최고의 누수 전문가. 정확한 진단, 확실한 시공.',
      specialties: JSON.stringify(['누수탐지', '방수공사', '타일공사']),
      verified: true,
      verifiedAt: new Date('2025-01-20'),
    },
    {
      name: '양재 보일러119',
      phone: '02-574-1919',
      serviceArea: '서초구, 강남구',
      latitude: 37.4679,
      longitude: 127.0346,
      rating: 4.6,
      reviewCount: 71,
      completedJobs: 213,
      trustScore: 86.4,
      responseTime: 30,
      profileImage: '/contractors/boiler-tech-3.png',
      description: '보일러 전문 A/S 센터. 모든 브랜드 수리 가능.',
      specialties: JSON.stringify(['보일러수리', 'A/S', '정기점검']),
      verified: true,
      verifiedAt: new Date('2024-10-15'),
    },

    // 송파/강동권 (4개)
    {
      name: '송파 누수탐지센터',
      phone: '02-418-5555',
      serviceArea: '송파구, 강동구',
      latitude: 37.5145,
      longitude: 127.1060,
      rating: 4.7,
      reviewCount: 98,
      completedJobs: 287,
      trustScore: 89.1,
      responseTime: 22,
      profileImage: '/contractors/plumber-1.png',
      description: '첨단 누수탐지 장비로 정확한 위치 파악.',
      specialties: JSON.stringify(['누수탐지', '배관수리', '방수']),
      verified: true,
      verifiedAt: new Date('2025-02-10'),
    },
    {
      name: '잠실 배관서비스',
      phone: '02-423-6677',
      serviceArea: '송파구',
      latitude: 37.5133,
      longitude: 127.1028,
      rating: 4.8,
      reviewCount: 145,
      completedJobs: 398,
      trustScore: 92.7,
      responseTime: 18,
      profileImage: '/contractors/pipe-specialist-2.png',
      description: '잠실 아파트 단지 전문. 신속한 출동, 정확한 시공.',
      specialties: JSON.stringify(['배관공사', '수도배관', '하수구']),
      verified: true,
      verifiedAt: new Date('2024-12-28'),
    },
    {
      name: '강동 전기설비',
      phone: '02-482-3030',
      serviceArea: '강동구, 송파구',
      latitude: 37.5301,
      longitude: 127.1238,
      rating: 4.5,
      reviewCount: 63,
      completedJobs: 189,
      trustScore: 83.6,
      responseTime: 35,
      profileImage: '/contractors/electrician-4.png',
      description: '전기, 조명 전문 업체입니다.',
      specialties: JSON.stringify(['전기공사', '조명', '콘센트']),
      verified: false,
    },
    {
      name: '천호 주방설비',
      phone: '02-485-4949',
      serviceArea: '강동구',
      latitude: 37.5385,
      longitude: 127.1236,
      rating: 4.4,
      reviewCount: 37,
      completedJobs: 112,
      trustScore: 79.8,
      responseTime: 40,
      profileImage: '/contractors/sink-expert-5.png',
      description: '주방 싱크대, 가스레인지 전문.',
      specialties: JSON.stringify(['싱크대', '가스', '주방리모델링']),
      verified: false,
    },

    // 영등포/강서권 (4개)
    {
      name: '여의도 프리미엄설비',
      phone: '02-785-1111',
      serviceArea: '영등포구, 마포구',
      latitude: 37.5219,
      longitude: 126.9245,
      rating: 4.9,
      reviewCount: 221,
      completedJobs: 612,
      trustScore: 96.2,
      responseTime: 10,
      profileImage: '/contractors/plumber-1.png',
      description: '고급 빌딩, 오피스텔 전문. 최고급 자재만 사용.',
      specialties: JSON.stringify(['고급설비', '누수', '배관']),
      verified: true,
      verifiedAt: new Date('2024-09-15'),
    },
    {
      name: '목동 배관클리닉',
      phone: '02-2642-7878',
      serviceArea: '양천구, 강서구',
      latitude: 37.5263,
      longitude: 126.8751,
      rating: 4.7,
      reviewCount: 112,
      completedJobs: 334,
      trustScore: 88.9,
      responseTime: 25,
      profileImage: '/contractors/pipe-specialist-2.png',
      description: '목동 지역 15년 경력. 친절한 상담.',
      specialties: JSON.stringify(['배관', '수도', '하수']),
      verified: true,
      verifiedAt: new Date('2025-01-05'),
    },
    {
      name: '강서 보일러전문',
      phone: '02-2665-5959',
      serviceArea: '강서구, 양천구',
      latitude: 37.5509,
      longitude: 126.8495,
      rating: 4.6,
      reviewCount: 84,
      completedJobs: 256,
      trustScore: 85.7,
      responseTime: 28,
      profileImage: '/contractors/boiler-tech-3.png',
      description: '보일러 설치, 수리, 점검 전문.',
      specialties: JSON.stringify(['보일러', '난방', '온수']),
      verified: true,
      verifiedAt: new Date('2024-11-10'),
    },
    {
      name: '화곡 전기마스터',
      phone: '02-2699-6060',
      serviceArea: '강서구',
      latitude: 37.5418,
      longitude: 126.8402,
      rating: 4.3,
      reviewCount: 48,
      completedJobs: 145,
      trustScore: 77.2,
      responseTime: 45,
      profileImage: '/contractors/electrician-4.png',
      description: '전기 관련 모든 것을 해결해드립니다.',
      specialties: JSON.stringify(['전기', '조명', '분전반']),
      verified: false,
    },

    // 강북/성북권 (3개)
    {
      name: '강북 누수119',
      phone: '02-991-1919',
      serviceArea: '강북구, 성북구',
      latitude: 37.6398,
      longitude: 127.0254,
      rating: 4.8,
      reviewCount: 156,
      completedJobs: 423,
      trustScore: 91.8,
      responseTime: 20,
      profileImage: '/contractors/plumber-1.png',
      description: '강북 지역 누수 전문가. 24시간 상담 가능.',
      specialties: JSON.stringify(['누수', '배관', '방수']),
      verified: true,
      verifiedAt: new Date('2024-12-15'),
    },
    {
      name: '성북 종합설비',
      phone: '02-928-3456',
      serviceArea: '성북구, 동대문구',
      latitude: 37.5894,
      longitude: 127.0167,
      rating: 4.7,
      reviewCount: 94,
      completedJobs: 278,
      trustScore: 87.4,
      responseTime: 26,
      profileImage: '/contractors/pipe-specialist-2.png',
      description: '성북구 일대 설비 전문. 정직 시공.',
      specialties: JSON.stringify(['종합설비', '배관', '보일러']),
      verified: true,
      verifiedAt: new Date('2025-01-25'),
    },
    {
      name: '미아 보일러센터',
      phone: '02-987-7070',
      serviceArea: '강북구',
      latitude: 37.6133,
      longitude: 127.0294,
      rating: 4.5,
      reviewCount: 67,
      completedJobs: 201,
      trustScore: 82.3,
      responseTime: 33,
      profileImage: '/contractors/boiler-tech-3.png',
      description: '보일러 전문 A/S. 합리적인 가격.',
      specialties: JSON.stringify(['보일러', '난방', '점검']),
      verified: false,
    },

    // 마포/용산권 (3개)
    {
      name: '마포 누수탐지',
      phone: '02-332-8989',
      serviceArea: '마포구, 서대문구',
      latitude: 37.5663,
      longitude: 126.9019,
      rating: 4.8,
      reviewCount: 167,
      completedJobs: 445,
      trustScore: 93.1,
      responseTime: 17,
      profileImage: '/contractors/plumber-1.png',
      description: '첨단 장비로 정확한 누수 탐지. 신속한 시공.',
      specialties: JSON.stringify(['누수탐지', '배관', '방수공사']),
      verified: true,
      verifiedAt: new Date('2024-10-20'),
    },
    {
      name: '용산 배관프로',
      phone: '02-792-5656',
      serviceArea: '용산구, 중구',
      latitude: 37.5326,
      longitude: 126.9905,
      rating: 4.6,
      reviewCount: 89,
      completedJobs: 267,
      trustScore: 84.9,
      responseTime: 29,
      profileImage: '/contractors/pipe-specialist-2.png',
      description: '용산 일대 배관 전문 업체.',
      specialties: JSON.stringify(['배관', '수도', '하수']),
      verified: true,
      verifiedAt: new Date('2025-02-05'),
    },
    {
      name: '홍대 전기설비',
      phone: '02-325-4141',
      serviceArea: '마포구',
      latitude: 37.5563,
      longitude: 126.9235,
      rating: 4.4,
      reviewCount: 52,
      completedJobs: 163,
      trustScore: 80.5,
      responseTime: 38,
      profileImage: '/contractors/electrician-4.png',
      description: '홍대 상권 전기 전문.',
      specialties: JSON.stringify(['전기', '조명', '간판']),
      verified: false,
    },

    // 기타 지역 (3개)
    {
      name: '노원 종합설비',
      phone: '02-933-2233',
      serviceArea: '노원구, 도봉구',
      latitude: 37.6542,
      longitude: 127.0568,
      rating: 4.7,
      reviewCount: 103,
      completedJobs: 312,
      trustScore: 88.6,
      responseTime: 24,
      profileImage: '/contractors/plumber-1.png',
      description: '노원구 설비 전문. 신속 출동.',
      specialties: JSON.stringify(['누수', '배관', '보일러']),
      verified: true,
      verifiedAt: new Date('2024-11-30'),
    },
    {
      name: '관악 배관센터',
      phone: '02-887-9999',
      serviceArea: '관악구, 금천구',
      latitude: 37.4783,
      longitude: 126.9516,
      rating: 4.5,
      reviewCount: 76,
      completedJobs: 234,
      trustScore: 83.1,
      responseTime: 31,
      profileImage: '/contractors/pipe-specialist-2.png',
      description: '관악구 일대 배관 전문.',
      specialties: JSON.stringify(['배관', '누수', '하수']),
      verified: true,
      verifiedAt: new Date('2025-01-12'),
    },
    {
      name: '광진 싱크대수리',
      phone: '02-455-7272',
      serviceArea: '광진구, 성동구',
      latitude: 37.5384,
      longitude: 127.0822,
      rating: 4.3,
      reviewCount: 41,
      completedJobs: 128,
      trustScore: 76.4,
      responseTime: 42,
      profileImage: '/contractors/sink-expert-5.png',
      description: '주방, 욕실 싱크대 전문.',
      specialties: JSON.stringify(['싱크대', '수전', '배수']),
      verified: false,
    },
  ]

  const contractors = []
  for (const data of contractorData) {
    const contractor = await prisma.contractor.create({ data })
    contractors.push(contractor)
  }

  console.log(`✅ ${contractors.length}개의 설비 업체 생성 완료`)

  // 고객 요청 데이터 (10개)
  const requestData = [
    {
      title: '화장실 누수 긴급 수리',
      description: '화장실 천장에서 물이 떨어집니다. 빠른 조치가 필요합니다.',
      address: '서울시 강남구 역삼동 123-45',
      latitude: 37.5012,
      longitude: 127.0396,
      status: 'COMPLETED',
    },
    {
      title: '주방 배수구 막힘',
      description: '주방 싱크대 배수가 안 되고 있습니다. 물이 역류하네요.',
      address: '서울시 서초구 서초동 678-90',
      latitude: 37.4833,
      longitude: 127.0322,
      status: 'COMPLETED',
    },
    {
      title: '보일러 고장',
      description: '보일러가 작동하지 않아요. 추워서 급합니다.',
      address: '서울시 송파구 잠실동 234-56',
      latitude: 37.5133,
      longitude: 127.1028,
      status: 'COMPLETED',
    },
    {
      title: '변기 물 안 내려감',
      description: '화장실 변기 물이 잘 안 내려가요.',
      address: '서울시 마포구 상암동 345-67',
      latitude: 37.5663,
      longitude: 126.9019,
      status: 'COMPLETED',
    },
    {
      title: '세면대 수전 교체',
      description: '세면대 수전이 너무 낡아서 교체하고 싶습니다.',
      address: '서울시 강동구 천호동 456-78',
      latitude: 37.5385,
      longitude: 127.1236,
      status: 'MATCHED',
    },
    {
      title: '욕실 배수구 냄새',
      description: '욕실 배수구에서 악취가 납니다.',
      address: '서울시 영등포구 여의도동 567-89',
      latitude: 37.5219,
      longitude: 126.9245,
      status: 'MATCHED',
    },
    {
      title: '싱크대 하부 누수',
      description: '싱크대 아래쪽에서 물이 샙니다.',
      address: '서울시 양천구 목동 123-12',
      latitude: 37.5263,
      longitude: 126.8751,
      status: 'PENDING',
    },
    {
      title: '수도 배관 동파',
      description: '겨울에 수도 배관이 얼어서 터진 것 같아요.',
      address: '서울시 강북구 미아동 234-23',
      latitude: 37.6133,
      longitude: 127.0294,
      status: 'PENDING',
    },
    {
      title: '전기 누전 의심',
      description: '전기가 자꾸 나가요. 누전 같습니다.',
      address: '서울시 성북구 정릉동 345-34',
      latitude: 37.5894,
      longitude: 127.0167,
      status: 'PENDING',
    },
    {
      title: '가스레인지 점화 안됨',
      description: '가스레인지 불이 안 켜져요.',
      address: '서울시 관악구 봉천동 456-45',
      latitude: 37.4783,
      longitude: 126.9516,
      status: 'PENDING',
    },
  ]

  const requests = []
  for (const data of requestData) {
    const request = await prisma.customerRequest.create({ data })
    requests.push(request)
  }

  console.log(`✅ ${requests.length}개의 고객 요청 생성 완료`)

  // 리뷰 데이터 (60개 - 업체별로 분산)
  const reviewData = [
    // 여의도 프리미엄설비 (10개 - 최고 평점)
    { contractorId: contractors[12].id, requestId: requests[0].id, customerName: '김철수', rating: 5, comment: '정말 친절하고 꼼꼼하게 작업해주셨어요. 강추합니다!' },
    { contractorId: contractors[12].id, requestId: requests[1].id, customerName: '이영희', rating: 5, comment: '누수 원인을 정확히 찾아서 깔끔하게 해결해주셨습니다.' },
    { contractorId: contractors[12].id, requestId: requests[2].id, customerName: '박민수', rating: 5, comment: '야간 긴급출동도 빠르게 와주셨어요. 감사합니다!' },
    { contractorId: contractors[12].id, requestId: requests[0].id, customerName: '정수진', rating: 5, comment: '가격도 합리적이고 시공 품질도 최고예요.' },
    { contractorId: contractors[12].id, requestId: requests[1].id, customerName: '최동욱', rating: 5, comment: '15년 경력이 느껴지는 숙련된 솜씨입니다.' },
    { contractorId: contractors[12].id, requestId: requests[2].id, customerName: '강미영', rating: 5, comment: 'A/S까지 완벽하게 해주셔서 만족스럽습니다.' },
    { contractorId: contractors[12].id, requestId: requests[0].id, customerName: '윤서준', rating: 5, comment: '다음에도 꼭 이 업체 이용할게요!' },
    { contractorId: contractors[12].id, requestId: requests[1].id, customerName: '한지우', rating: 5, comment: '설명도 자세히 해주시고 정말 프로페셔널하세요.' },
    { contractorId: contractors[12].id, requestId: requests[0].id, customerName: '임하은', rating: 4, comment: '전반적으로 만족하지만 가격이 조금 비싼 편이에요.' },
    { contractorId: contractors[12].id, requestId: requests[1].id, customerName: '조민재', rating: 5, comment: '여의도에서 최고 업체인 것 같아요. 강력추천!' },

    // 반포 누수센터 (9개)
    { contractorId: contractors[6].id, requestId: requests[0].id, customerName: '송하늘', rating: 5, comment: '누수 탐지 장비가 정말 첨단이에요. 정확해요!' },
    { contractorId: contractors[6].id, requestId: requests[1].id, customerName: '배서윤', rating: 5, comment: '12분만에 출동하셨어요. 놀라운 속도!' },
    { contractorId: contractors[6].id, requestId: requests[2].id, customerName: '허준호', rating: 5, comment: '시공 후 2년 보증까지 해주셔서 안심이에요.' },
    { contractorId: contractors[6].id, requestId: requests[0].id, customerName: '홍길동', rating: 5, comment: '반포에서 누수 문제 있으면 여기가 최고입니다.' },
    { contractorId: contractors[6].id, requestId: requests[1].id, customerName: '안유진', rating: 5, comment: '친절하고 정직한 업체예요. 믿을 수 있어요.' },
    { contractorId: contractors[6].id, requestId: requests[2].id, customerName: '서이안', rating: 4, comment: '시공은 완벽한데 연락이 조금 늦었어요.' },
    { contractorId: contractors[6].id, requestId: requests[0].id, customerName: '권도윤', rating: 5, comment: '방수 공사까지 함께 해주셔서 깔끔합니다.' },
    { contractorId: contractors[6].id, requestId: requests[1].id, customerName: '문소율', rating: 5, comment: '가족 같은 따뜻함을 느꼈어요. 감사합니다.' },
    { contractorId: contractors[6].id, requestId: requests[2].id, customerName: '유찬영', rating: 5, comment: '20년 넘게 반포에서 하신 이유를 알 것 같아요!' },

    // 서초 배관마스터 (8개)
    { contractorId: contractors[1].id, requestId: requests[0].id, customerName: '오시우', rating: 5, comment: '서울대 출신이라 그런지 설명이 논리적이고 명확해요.' },
    { contractorId: contractors[1].id, requestId: requests[1].id, customerName: '남다온', rating: 5, comment: '배관 구조를 완전히 새로 잡아주셨어요. 대만족!' },
    { contractorId: contractors[1].id, requestId: requests[2].id, customerName: '채시후', rating: 5, comment: '정직한 견적, 깔끔한 시공. 완벽합니다.' },
    { contractorId: contractors[1].id, requestId: requests[0].id, customerName: '탁주원', rating: 4, comment: '실력은 좋은데 예약이 밀려서 조금 기다렸어요.' },
    { contractorId: contractors[1].id, requestId: requests[1].id, customerName: '설아린', rating: 5, comment: '합리적인 가격에 최고 품질이에요!' },
    { contractorId: contractors[1].id, requestId: requests[2].id, customerName: '표지안', rating: 5, comment: '이웃 추천으로 왔는데 정말 잘 하시네요.' },
    { contractorId: contractors[1].id, requestId: requests[0].id, customerName: '변수아', rating: 5, comment: 'A/S 기간에 무료로 재방문해주셨어요.' },
    { contractorId: contractors[1].id, requestId: requests[1].id, customerName: '도준서', rating: 5, comment: '서초구에서는 여기가 원탑인 듯!' },

    // 강남 누수119 (7개)
    { contractorId: contractors[0].id, requestId: requests[0].id, customerName: '석하린', rating: 5, comment: '18분 만에 출동! 정말 빠르고 정확해요.' },
    { contractorId: contractors[0].id, requestId: requests[1].id, customerName: '진아윤', rating: 5, comment: '15년 경력이 확실히 다르네요. 실력 최고!' },
    { contractorId: contractors[0].id, requestId: requests[2].id, customerName: '황시은', rating: 5, comment: '욕실 리모델링까지 함께 했는데 완전 만족!' },
    { contractorId: contractors[0].id, requestId: requests[0].id, customerName: '예서진', rating: 4, comment: '시공은 완벽한데 가격이 조금 세요.' },
    { contractorId: contractors[0].id, requestId: requests[1].id, customerName: '소민준', rating: 5, comment: '강남에서 누수 문제면 여기 추천합니다!' },
    { contractorId: contractors[0].id, requestId: requests[2].id, customerName: '나유준', rating: 5, comment: '친절하고 꼼꼼한 설명 감사해요.' },
    { contractorId: contractors[0].id, requestId: requests[0].id, customerName: '추지호', rating: 5, comment: '야간 긴급 출동도 가능해서 정말 좋아요!' },

    // 잠실 배관서비스 (6개)
    { contractorId: contractors[9].id, requestId: requests[0].id, customerName: '염예준', rating: 5, comment: '잠실 아파트 구조를 완전히 꿰고 계세요!' },
    { contractorId: contractors[9].id, requestId: requests[1].id, customerName: '신도현', rating: 5, comment: '18분 출동, 1시간 완료. 감동입니다.' },
    { contractorId: contractors[9].id, requestId: requests[2].id, customerName: '목서연', rating: 4, comment: '실력 좋고 친절해요. 조금 비싼 감은 있어요.' },
    { contractorId: contractors[9].id, requestId: requests[0].id, customerName: '뇌시온', rating: 5, comment: '수도 배관 교체 깔끔하게 해주셨어요!' },
    { contractorId: contractors[9].id, requestId: requests[1].id, customerName: '감도윤', rating: 5, comment: '이웃들한테도 추천했어요. 최고!' },
    { contractorId: contractors[9].id, requestId: requests[2].id, customerName: '빈유진', rating: 5, comment: '잠실에서는 여기가 답인 것 같습니다.' },

    // 마포 누수탐지 (6개)
    { contractorId: contractors[18].id, requestId: requests[0].id, customerName: '여민서', rating: 5, comment: '첨단 장비로 누수 위치 정확히 찾아주셨어요!' },
    { contractorId: contractors[18].id, requestId: requests[1].id, customerName: '당은우', rating: 5, comment: '17분 출동, 정말 빨라요. 감사합니다!' },
    { contractorId: contractors[18].id, requestId: requests[2].id, customerName: '길지우', rating: 5, comment: '방수 공사까지 원스톱으로 해결!' },
    { contractorId: contractors[18].id, requestId: requests[0].id, customerName: '노서준', rating: 4, comment: '시공은 완벽, 견적이 조금 높았어요.' },
    { contractorId: contractors[18].id, requestId: requests[1].id, customerName: '두하준', rating: 5, comment: '마포에서 누수면 무조건 여기!' },
    { contractorId: contractors[18].id, requestId: requests[2].id, customerName: '옥지훈', rating: 5, comment: '친절하고 정직한 업체입니다. 강추!' },

    // 강북 누수119 (5개)
    { contractorId: contractors[15].id, requestId: requests[0].id, customerName: '로하윤', rating: 5, comment: '강북에서 최고 업체예요. 24시간 상담 가능!' },
    { contractorId: contractors[15].id, requestId: requests[1].id, customerName: '수지아', rating: 5, comment: '배관 수리 완벽하게 해주셨어요.' },
    { contractorId: contractors[15].id, requestId: requests[2].id, customerName: '지수빈', rating: 4, comment: '좋은데 대기 시간이 조금 있었어요.' },
    { contractorId: contractors[15].id, requestId: requests[0].id, customerName: '견예은', rating: 5, comment: '정직한 가격, 확실한 시공!' },
    { contractorId: contractors[15].id, requestId: requests[1].id, customerName: '하윤아', rating: 5, comment: '다음에도 꼭 이 업체에 맡길게요!' },

    // 성북 종합설비 (5개)
    { contractorId: contractors[16].id, requestId: requests[0].id, customerName: '곽채원', rating: 5, comment: '성북구 일대 종합설비는 여기가 최고!' },
    { contractorId: contractors[16].id, requestId: requests[1].id, customerName: '팽소율', rating: 4, comment: '정직하게 시공하시는데 약간 느려요.' },
    { contractorId: contractors[16].id, requestId: requests[2].id, customerName: '우다은', rating: 5, comment: '보일러 교체 깔끔하게 해주셨어요.' },
    { contractorId: contractors[16].id, requestId: requests[0].id, customerName: '엽수민', rating: 5, comment: '합리적인 가격, 친절한 상담!' },
    { contractorId: contractors[16].id, requestId: requests[1].id, customerName: '편가을', rating: 5, comment: '이웃 추천으로 왔는데 정말 만족해요!' },

    // 목동 배관클리닉 (4개)
    { contractorId: contractors[13].id, requestId: requests[0].id, customerName: '계지율', rating: 5, comment: '목동 15년 경력, 확실히 믿음이 가요!' },
    { contractorId: contractors[13].id, requestId: requests[1].id, customerName: '호현우', rating: 4, comment: '친절한 상담, 시공도 만족스러워요.' },
    { contractorId: contractors[13].id, requestId: requests[2].id, customerName: '평보경', rating: 5, comment: '하수 배관 막힘 완벽 해결!' },
    { contractorId: contractors[13].id, requestId: requests[0].id, customerName: '옹서우', rating: 5, comment: '양천구에서는 여기가 답입니다!' },
  ]

  const reviews = []
  for (const data of reviewData) {
    const review = await prisma.review.create({ data })
    reviews.push(review)
  }

  console.log(`✅ ${reviews.length}개의 리뷰 생성 완료`)
  console.log('🎉 시드 데이터 삽입 완료!')
}

main()
  .catch((e) => {
    console.error('❌ 시드 데이터 삽입 실패:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
